### ISSUE TITLE
Wwhisper - Marker Creator Crashing when exiting the script

### ISSUE THREAD

**Issue by gfazzito** [TFKusa/kusa_reascripts#1]
When clicking the script on the GUI windows, the script crashes with the following legend:

...s\Regions and Markers\kusa_Wwhisper - Marker Creator.lua:119: attempt to call a nil value (field 'ImGui_DestroyContext')

![image](https://github.com/user-attachments/assets/661db1a6-4e6a-49d8-997d-8f32aa177715)

**Comment by TFKusa** [comment]
@gfazzito Marker Creator is depreciated, please use Wwhisper Assistant instead.
More info : https://github.com/TFKusa/kusa_reascripts/blob/master/Documentation/WWHISPER%20-%20DOCUMENTATION.md
